require 'thread'
require 'yaml'
require 'active_support/core_ext/string/inflections'
require 'redcarpet'
require 'stringio'
require 'eventmachine'
require 'serialport'
require 'amqp'
require 'json'

require 'smartkiosk/common'

require 'smartware/version'
require 'smartware/logging'
require 'smartware/service'
require 'smartware/process_manager'
require 'smartware/interfaces/interface'
require 'smartware/interfaces/cash_acceptor'
require 'smartware/interfaces/modem'
require 'smartware/interfaces/printer'
require 'smartware/interfaces/watchdog'
require 'smartware/interfaces/card_reader'
require 'smartware/connection_monitor'
